
version: 2

sources:
  - name: keyvan
    database: db
    schema: myschm
    tables:
      - name: customers
        columns: 
          - name: customerid
            tests:
              - not_null
              - unique
      - name: orders
        columns: 
          - name: orderid
            tests:
              - not_null
              - unique
      
